### ISSUE TITLE
[Question] How to build this game to AWS ec2?

### ISSUE THREAD

**Issue by hunglsxx** [endel/colyseus-tic-tac-toe#6]
Hello,
I have a EC2 instance ubuntu 18 and domain, i installed apache2 as a proxy pass
But, i don't know how to build this. When i try run bold server and client via 2 port, and pass domain to this ports, i'm got an error: http://localhost:9000/sockjs-node/info?t=1586107652654. what'is localhost when i used my public domain? :(

**Comment by endel** [comment]
Hi, deployment instructions can be found at https://docs.colyseus.io/deployment/
