### ISSUE TITLE
Question: single dimension array for board?

### ISSUE THREAD

**Issue by krcourville** [endel/colyseus-tic-tac-toe#7]
Hi, 

this sample code has been quite helpful. I am curious of the reason for using a single dimension array vs a 2d array for the board. 

Better performance? Simplified (or required for serialization? personal preference?

**Comment by endel** [comment]
Hi @krcourville, glad you found it helpful. (this example haven't been upgraded to v0.13 yet)

I'm using a single dimension array because the serializer (`@colyseus/schema`) does not support multi-dimensional. 

Cheers!

**Comment by krcourville** [comment]
Thanks, I see now:

> Multi-dimensional arrays are not supported. See how to use 1D arrays as multi-dimensional
