### ISSUE TITLE
What does MapSchema do?

### ISSUE THREAD

**Issue by nitwhiz** [endel/colyseus-tic-tac-toe#8]
I don't get what I'm reading here:

https://github.com/endel/colyseus-tic-tac-toe/blob/7fc04f44a9e3fc031196ec11ba95bba323d0c4c1/server/rooms/tictactoe.ts#L9

While it's used once as

https://github.com/endel/colyseus-tic-tac-toe/blob/7fc04f44a9e3fc031196ec11ba95bba323d0c4c1/server/rooms/tictactoe.ts#L25

and only it's keys are used elsewhere.

**Comment by endel** [comment]
Hi, the `@type()` annotations configure which properties will be serialized over the network. The client side gets updates automatically.

On Colyseus, the [server side is responsible for mutating a shared state](https://github.com/endel/colyseus-tic-tac-toe/blob/48ee7ae4da88da6b0dab562339625878017e0e3d/server/rooms/tictactoe.ts#L48-L60) between all clients, and the [clients only listen for such changes in such properties](https://github.com/endel/colyseus-tic-tac-toe/blob/48ee7ae4da88da6b0dab562339625878017e0e3d/javascript-pixi/src/screens/GameScreen.js#L47-L63).

`MapSchema` is a regular map that can synchronize its additions and removals. 

(Sorry for taking this long to reply here! Let me know if you have any other questions!)
